### ISSUE TITLE
Some cursor movements will show the file as 'dirty'

### ISSUE THREAD

**Issue by dschuyler** [google/ci_edit#83]
If I open a large file and use ctrl+g, t (or b) to jump to the top or bottom of the file (with no other edits in the file), the file will be seen as dirty. Dirty meaning that the * is shown next to the file path and ctrl-q will prompt to ask about saving the modified file.

It looks like removing ```and self.redoIndex != len(self.redoChain)``` from the following code in app/mutator.py will fix the issue. I don't recall why that test is part of that if-statment. 

aaxu@ do you recall?

```
    # When the redoChain is trimmed we may lose the saved at.
    # Trim only when there is a non-trivial action.
    if change[0] == 'm' and self.redoIndex != len(self.redoChain):
      newTrivialChange = True
    else:
```

**Comment by aaxu** [comment]
I'm opening files and I'm able to produce this particular issue. Maybe the file isn't big enough? I'm opening up a book in plain text that is about 732kb and 13427 lines long.  Is there a reason why this only happens in large files? The reason I kept that if statement in was because we don't have to worry about truncation if we are at the end of the redo chain.

**Comment by dschuyler** [comment]
I've removed the check. Please help me keep an eye out for problems this may cause :)

**Comment by aaxu** [comment]
I put the check back in and was unable to reproduce this issue. Quite confused now.. What were the steps you used to reproduce it?
